import io, uuid

NS = uuid.UUID("6b1d6f0e-3b1a-4f1c-9a51-0a7e5e2a0c11")
def gid(*parts): return str(uuid.uuid5(NS, "|".join(parts)))

MOTO, CAR = "Motorcycle", "Car"

items = {
    MOTO: [
        ("part", "روغن و فیلتر", ["روغن موتور", "فیلتر روغن", "فیلتر هوا", "فیلتر بنزین", "روغن گیربکس (اسکوتر)", "روغن کمک جلو"]),
        ("part", "موتور", ["شمع", "واشر سرسیلندر", "پیستون و رینگ", "کاسه‌نمد", "کاربراتور"]),
        ("part", "ترمز", ["لنت ترمز جلو", "لنت ترمز عقب", "کفشک ترمز", "روغن ترمز", "سیم ترمز"]),
        ("part", "انتقال قدرت", ["زنجیر", "دنده جلو (گیربکس)", "طبق‌دنده عقب", "تسمه CVT", "وزنه (رولر) کلاچ", "صفحه کلاچ", "سیم کلاچ", "سیم گاز"]),
        ("part", "برق", ["باتری", "لامپ چراغ جلو", "رله راهنما", "کویل", "استارت"]),
        ("part", "چرخ", ["لاستیک جلو", "لاستیک عقب", "تیوب", "بلبرینگ چرخ"]),
        ("labor", "اجرت و خدمات", ["تعویض روغن", "سرویس دوره‌ای", "سرویس کاربراتور", "تنظیم سوپاپ", "تعویض لنت", "تعویض کیت زنجیر",
                                   "سرویس CVT", "تعمیر کلاچ", "تعمیر موتور (کامل)", "عیب‌یابی برق", "تعمیر استارت", "تعویض یا پنچرگیری لاستیک"]),
    ],
    CAR: [
        ("part", "روغن و فیلتر", ["روغن موتور (لیتر)", "فیلتر روغن", "فیلتر هوا", "فیلتر کابین", "فیلتر بنزین", "روغن گیربکس (لیتر)", "ضدیخ (لیتر)", "روغن هیدرولیک فرمان"]),
        ("part", "موتور", ["شمع", "کویل", "وایر شمع", "تسمه تایم", "بلبرینگ تسمه‌سفت‌کن", "تسمه دینام", "واتر پمپ", "واشر سرسیلندر"]),
        ("part", "ترمز", ["لنت ترمز جلو", "لنت ترمز عقب", "دیسک ترمز", "روغن ترمز"]),
        ("part", "جلوبندی و تعلیق", ["کمک‌فنر جلو", "کمک‌فنر عقب", "سیبک فرمان", "طبق", "بوش طبق", "بلبرینگ چرخ"]),
        ("part", "کلاچ", ["دیسک و صفحه کلاچ", "بلبرینگ کلاچ"]),
        ("part", "برق و کولر", ["باتری", "لامپ چراغ جلو", "تیغه برف‌پاک‌کن", "گاز کولر"]),
        ("part", "چرخ", ["لاستیک"]),
        ("labor", "اجرت و خدمات", ["تعویض روغن و فیلتر", "سرویس دوره‌ای", "تعویض لنت", "تعویض تسمه تایم", "تعمیر کلاچ", "تعویض کمک‌فنر",
                                   "عیب‌یابی و دیاگ", "شستشوی انژکتور", "شارژ گاز کولر", "تعویض باتری", "تعمیر جلوبندی", "تعمیر گیربکس",
                                   "تعمیر موتور (کامل)", "تعویض روغن گیربکس", "پنچرگیری و بالانس"]),
    ],
}

packages = {
    MOTO: [
        ("تعویض روغن", "روغن موتور و اجرت؛ فیلتر روغن اختیاری", [("روغن موتور", 1, False), ("فیلتر روغن", 1, True), ("تعویض روغن", 1, False)]),
        ("سرویس دوره‌ای", "روغن، فیلترها، شمع و اجرت سرویس", [("روغن موتور", 1, False), ("فیلتر روغن", 1, False), ("فیلتر هوا", 1, False), ("شمع", 1, False), ("سرویس دوره‌ای", 1, False)]),
        ("سرویس ترمز", "لنت و اجرت؛ روغن ترمز اختیاری", [("لنت ترمز جلو", 1, False), ("لنت ترمز عقب", 1, True), ("روغن ترمز", 1, True), ("تعویض لنت", 1, False)]),
        ("تعویض کیت زنجیر", "زنجیر، دنده جلو، طبق‌دنده و اجرت", [("زنجیر", 1, False), ("دنده جلو (گیربکس)", 1, False), ("طبق‌دنده عقب", 1, False), ("تعویض کیت زنجیر", 1, False)]),
        ("سرویس CVT", "تسمه، وزنه‌ها و اجرت (اسکوتر)", [("تسمه CVT", 1, False), ("وزنه (رولر) کلاچ", 1, True), ("سرویس CVT", 1, False)]),
    ],
    CAR: [
        ("تعویض روغن", "روغن موتور، فیلتر روغن و اجرت", [("روغن موتور (لیتر)", 4, False), ("فیلتر روغن", 1, False), ("تعویض روغن و فیلتر", 1, False)]),
        ("سرویس دوره‌ای", "روغن، فیلترها و اجرت؛ شمع اختیاری", [("روغن موتور (لیتر)", 4, False), ("فیلتر روغن", 1, False), ("فیلتر هوا", 1, False), ("فیلتر کابین", 1, False), ("شمع", 4, True), ("سرویس دوره‌ای", 1, False)]),
        ("سرویس ترمز", "لنت جلو و اجرت؛ دیسک و روغن ترمز اختیاری", [("لنت ترمز جلو", 1, False), ("دیسک ترمز", 2, True), ("روغن ترمز", 1, True), ("تعویض لنت", 1, False)]),
        ("تعویض تسمه تایم", "تسمه، بلبرینگ و اجرت؛ واتر پمپ اختیاری", [("تسمه تایم", 1, False), ("بلبرینگ تسمه‌سفت‌کن", 1, False), ("واتر پمپ", 1, True), ("تسمه دینام", 1, True), ("تعویض تسمه تایم", 1, False)]),
        ("سرویس کولر", "گاز کولر و اجرت شارژ", [("گاز کولر", 1, False), ("شارژ گاز کولر", 1, False)]),
    ],
}

def cs(s): return '"' + s.replace('"', '\\"') + '"'
out = ["// <auto-generated> by tools/gen_standard_catalog.py; edit the lists there and regenerate. Ids are stable (UUID v5).",
       "namespace Arte.Core.Billing;", "",
       "/// <summary>The starter list every business sees: common goods and jobs per vehicle group, and ready-made packages.</summary>",
       "public static class StandardCatalogSeed", "{"]
item_ids = {}
rows = []
order = 0
for group, cats in items.items():
    for kind, cat, titles in cats:
        for t in titles:
            order += 1
            i = gid("item", group, t)
            item_ids[(group, t)] = i
            rows.append(f'        new() {{ Id = new Guid("{i}"), Kind = {cs(kind)}, Category = {cs(cat)}, Title = {cs(t)}, VehicleKinds = VehicleGroups.{group}, SortOrder = {order} }},')
out.append("    public static StandardItem[] Items =>")
out.append("    [")
out += rows
out.append("    ];")
out.append("")
prow, lrow = [], []
porder = 0
for group, ps in packages.items():
    for title, desc, lines in ps:
        porder += 1
        p = gid("package", group, title)
        prow.append(f'        new() {{ Id = new Guid("{p}"), Title = {cs(title)}, Description = {cs(desc)}, VehicleKinds = VehicleGroups.{group}, SortOrder = {porder} }},')
        for n, (t, q, opt) in enumerate(lines, 1):
            lrow.append(f'        new() {{ Id = new Guid("{gid("line", group, title, t)}"), PackageId = new Guid("{p}"), StandardItemId = new Guid("{item_ids[(group, t)]}"), Quantity = {q}m, Optional = {"true" if opt else "false"}, SortOrder = {n} }},')
out += ["    public static ServicePackage[] Packages =>", "    ["] + prow + ["    ];", "", "    public static ServicePackageLine[] Lines =>", "    ["] + lrow + ["    ];", "}", ""]
io.open(r"F:\reza\ARTE-SERVICE\src\Arte.Core\Billing\StandardCatalogSeed.cs", "w", encoding="utf-8", newline="\n").write("\n".join(out))
print(len(rows), "items,", len(prow), "packages,", len(lrow), "lines")
