using Arte.Core.Common;
using Arte.Core.Tenancy;

namespace Arte.Core.Cases;

/// <summary>A photo on a case (work done, delivery, damage). The file lives on disk, never publicly reachable.</summary>
public sealed class CaseAttachment : ITenantOwned, ISoftDeletable
{
    public Guid Id { get; set; } = Guid.CreateVersion7();
    public Guid TenantId { get; set; }
    public Guid CaseId { get; set; }
    /// <summary>Stage the case was in when the photo was taken (received, repairing, review, ready, delivered…).</summary>
    public required string StageKey { get; set; }
    public required string ContentType { get; set; }
    public long SizeBytes { get; set; }
    /// <summary>Relative path under the storage root; generated by the server, never from user input.</summary>
    public required string StoragePath { get; set; }
    public string? Caption { get; set; }
    /// <summary>Shown on the customer's tracking page. Chosen at upload (default from Settings), changeable later.</summary>
    public bool VisibleToCustomer { get; set; }
    public Guid CreatedBy { get; set; }
    public DateTimeOffset CreatedAt { get; set; }
    public DateTimeOffset? DeletedAt { get; set; }
    public Guid? DeletedBy { get; set; }
}
